access:
  admin:
    username: 'youshouldchangethis'
    password: 'yesyoudo'
  oper:
    username: 'pleasechangethis'
    password: 'prettyplease'
  guest:
    username: 'youmustchangethisnow'
    password: 'changeitnowplease'
